version: '3'
services:
  web-server-prod:
    build:
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - mongo
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=prod --add-opens java.base/java.lang=ALL-UNNAMED"
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"